# Generated by Django 2.2.28 on 2023-05-31 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_animal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Acma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asd', models.BigIntegerField()),
            ],
        ),
    ]
